/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "my_led.h"
#include "my_switch.h"




#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	led_init();
	switch_init();
	while(1)
	{
		int press;
		press = switch_press_count();


		 if (press == 1)
		        {
		           led_green_on();

		        }
		        else if (press == 2)
		        {

		           led_blue_on();
		        }
		        else
		        led_off();
}
}







